/** Tên file tự sinh (paste, Instagram export, storage hash) — không hiển thị raw cho user. */

export function isAutoGeneratedFileName(name) {
  const n = String(name || '').trim();
  if (!n) return true;
  const base = n.split(/[/\\]/).pop() || n;
  if (/^[a-f0-9-]{32,}\./i.test(base)) return true;
  if (/_[a-f0-9]{20,}\.(jpe?g|png|gif|webp|heic|pdf|md|txt)$/i.test(base)) return true;
  if (/^\d{8,}[_-][\da-f-]+\.(jpe?g|png|gif|webp|heic|pdf|md|txt)$/i.test(base)) return true;
  if (base.length > 52 && /^[\d_a-f-]+\.[a-z0-9]+$/i.test(base)) return true;
  if (/^(blob|unknown)$/i.test(base)) return true;
  return false;
}

export function extensionFromFile(file) {
  const raw = String(file?.name || '').trim();
  const fromName = raw.includes('.') ? raw.split('.').pop()?.toLowerCase() : '';
  if (fromName && fromName.length <= 6) return fromName;

  const mime = String(file?.type || '').toLowerCase();
  if (mime === 'image/jpeg') return 'jpg';
  if (mime === 'image/png') return 'png';
  if (mime === 'image/gif') return 'gif';
  if (mime === 'image/webp') return 'webp';
  if (mime === 'image/heic' || mime === 'image/heif') return 'heic';
  if (mime === 'text/markdown') return 'md';
  if (mime === 'text/plain') return 'txt';
  if (mime === 'application/pdf') return 'pdf';
  return fromName || 'file';
}

/**
 * @param {File|Blob|null|undefined} file
 * @param {(key: string) => string} t
 */
export function resolveComposerFileDisplayName(file, t) {
  const raw = String(file?.name || '').trim();
  if (raw && !isAutoGeneratedFileName(raw)) return raw;

  const ext = extensionFromFile(file);
  if ((file?.type || '').startsWith('image/')) {
    return t('chat.composerAttachmentImageDefault').replace('{ext}', ext);
  }
  return t('chat.composerAttachmentFileDefault').replace('{ext}', ext);
}

/**
 * Đổi tên File trước preview/upload nếu tên gốc là hash dài.
 * @param {File} file
 * @param {(key: string) => string} t
 * @returns {File}
 */
export function normalizeComposerFile(file, t) {
  if (!file) return file;
  const displayName = resolveComposerFileDisplayName(file, t);
  if (!displayName || displayName === file.name) return file;
  try {
    return new File([file], displayName, {
      type: file.type || 'application/octet-stream',
      lastModified: file.lastModified,
    });
  } catch {
    return file;
  }
}
