import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  isAutoGeneratedFileName,
  resolveComposerFileDisplayName,
  normalizeComposerFile,
} from './composerAttachmentUtils.js';

const t = (key) =>
  ({
    'chat.composerAttachmentImageDefault': 'Ảnh.{ext}',
    'chat.composerAttachmentFileDefault': 'Tệp.{ext}',
  })[key] || key;

describe('composerAttachmentUtils', () => {
  it('isAutoGeneratedFileName nhận hash Instagram/export', () => {
    assert.equal(
      isAutoGeneratedFileName(
        '1787281948620_3635060662673106413_3635060662673106413_d8d0c6f388ef3aa8fccbad4fe49a931b.jpg'
      ),
      true
    );
    assert.equal(isAutoGeneratedFileName('demo.md'), false);
    assert.equal(isAutoGeneratedFileName('photo-holiday.jpg'), false);
  });

  it('resolveComposerFileDisplayName trả tên thân thiện cho ảnh hash', () => {
    const name = resolveComposerFileDisplayName(
      {
        name: '1787281948620_3635060662673106413_3635060662673106413_d8d0c6f388ef3aa8fccbad4fe49a931b.jpg',
        type: 'image/jpeg',
      },
      t
    );
    assert.equal(name, 'Ảnh.jpg');
  });

  it('normalizeComposerFile đổi tên File upload', () => {
    const raw = new File(
      ['x'],
      '1787281948620_3635060662673106413_3635060662673106413_d8d0c6f388ef3aa8fccbad4fe49a931b.jpg',
      { type: 'image/jpeg' }
    );
    const next = normalizeComposerFile(raw, t);
    assert.equal(next.name, 'Ảnh.jpg');
  });
});
